### PR TITLE
[WIP] initial import, postgis topology builder script

### PR DESCRIPTION
**Pull request by ltclm**

### CODE REVIEW

**Comment by loicgasser** [comment]
I will work on a version that can take a configuration file or parameters.

**Comment by ltclm** [comment]
i would like to use fme instead. please give me the list of douglas peucker tolerances and i will prepare the geometry columns.

**Comment by loicgasser** [comment]
I will work in a separate DB if topologies cause too many issues.

**Comment by loicgasser** [comment]
Ok thanks for solving the issue in DB.
as a reminder  we need to check:
```sql
SELECT count(pk_product) from geol.view_geocover_grid_shop WHERE substring(pk_product, 6) != s_map_number
```

**Pull request merged**
